version: '3.7'

services:
  # 1. Zookeeper Service (The Manager)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181" # Zookeeper default port
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 2. Kafka Broker Service (The "Post Office")
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      # Port for external connections (like your Spring Boot app)
      - "9092:9092"
    depends_on:
      - zookeeper # Zookeeper start aana apram dhaan Kafka start aaganum
    environment:
      KAFKA_BROKER_ID: 1
      # Zookeeper service oda per (internal Docker network name)
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      # Idhu dhaan important:
      # Spring Boot (ungaloda machine la irundhu) epdi connect pannanum nu solrom
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

